/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ForumIndexRouteImport } from './routes/forum.index'
import { Route as DoubtsIndexRouteImport } from './routes/doubts.index'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams_.$teamId'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as DoubtsDoubtIdRouteImport } from './routes/doubts.$doubtId'
import { Route as CoursesCourseCodeRouteImport } from './routes/courses_.$courseCode'
import { Route as BlogsNewRouteImport } from './routes/blogs.new'
import { Route as BlogsCourseCodeIndexRouteImport } from './routes/blogs.$courseCode.index'
import { Route as CoursesCourseCodeSubmissionsRouteImport } from './routes/courses_.$courseCode_.submissions'
import { Route as CoursesCourseCodeSectionRouteImport } from './routes/courses_.$courseCode_.section'
import { Route as BlogsCourseCodePostIdRouteImport } from './routes/blogs.$courseCode.$postId'

const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumIndexRoute = ForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoubtsIndexRoute = DoubtsIndexRouteImport.update({
  id: '/doubts/',
  path: '/doubts/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams_/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const DoubtsDoubtIdRoute = DoubtsDoubtIdRouteImport.update({
  id: '/doubts/$doubtId',
  path: '/doubts/$doubtId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseCodeRoute = CoursesCourseCodeRouteImport.update({
  id: '/courses_/$courseCode',
  path: '/courses/$courseCode',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsNewRoute = BlogsNewRouteImport.update({
  id: '/blogs/new',
  path: '/blogs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsCourseCodeIndexRoute = BlogsCourseCodeIndexRouteImport.update({
  id: '/blogs/$courseCode/',
  path: '/blogs/$courseCode/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseCodeSubmissionsRoute =
  CoursesCourseCodeSubmissionsRouteImport.update({
    id: '/courses_/$courseCode_/submissions',
    path: '/courses/$courseCode/submissions',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursesCourseCodeSectionRoute =
  CoursesCourseCodeSectionRouteImport.update({
    id: '/courses_/$courseCode_/section',
    path: '/courses/$courseCode/section',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogsCourseCodePostIdRoute = BlogsCourseCodePostIdRouteImport.update({
  id: '/blogs/$courseCode/$postId',
  path: '/blogs/$courseCode/$postId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/teams': typeof TeamsRoute
  '/blogs/new': typeof BlogsNewRoute
  '/courses/$courseCode': typeof CoursesCourseCodeRoute
  '/doubts/$doubtId': typeof DoubtsDoubtIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/blogs/': typeof BlogsIndexRoute
  '/doubts/': typeof DoubtsIndexRoute
  '/forum/': typeof ForumIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/blogs/$courseCode/$postId': typeof BlogsCourseCodePostIdRoute
  '/courses/$courseCode/section': typeof CoursesCourseCodeSectionRoute
  '/courses/$courseCode/submissions': typeof CoursesCourseCodeSubmissionsRoute
  '/blogs/$courseCode/': typeof BlogsCourseCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/teams': typeof TeamsRoute
  '/blogs/new': typeof BlogsNewRoute
  '/courses/$courseCode': typeof CoursesCourseCodeRoute
  '/doubts/$doubtId': typeof DoubtsDoubtIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/blogs': typeof BlogsIndexRoute
  '/doubts': typeof DoubtsIndexRoute
  '/forum': typeof ForumIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/blogs/$courseCode/$postId': typeof BlogsCourseCodePostIdRoute
  '/courses/$courseCode/section': typeof CoursesCourseCodeSectionRoute
  '/courses/$courseCode/submissions': typeof CoursesCourseCodeSubmissionsRoute
  '/blogs/$courseCode': typeof BlogsCourseCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/teams': typeof TeamsRoute
  '/blogs/new': typeof BlogsNewRoute
  '/courses_/$courseCode': typeof CoursesCourseCodeRoute
  '/doubts/$doubtId': typeof DoubtsDoubtIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/teams_/$teamId': typeof TeamsTeamIdRoute
  '/blogs/': typeof BlogsIndexRoute
  '/doubts/': typeof DoubtsIndexRoute
  '/forum/': typeof ForumIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/blogs/$courseCode/$postId': typeof BlogsCourseCodePostIdRoute
  '/courses_/$courseCode_/section': typeof CoursesCourseCodeSectionRoute
  '/courses_/$courseCode_/submissions': typeof CoursesCourseCodeSubmissionsRoute
  '/blogs/$courseCode/': typeof BlogsCourseCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/admin'
    | '/app'
    | '/auth'
    | '/courses'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/settings'
    | '/signup'
    | '/teams'
    | '/blogs/new'
    | '/courses/$courseCode'
    | '/doubts/$doubtId'
    | '/profile/$userId'
    | '/teams/$teamId'
    | '/blogs/'
    | '/doubts/'
    | '/forum/'
    | '/profile/'
    | '/blogs/$courseCode/$postId'
    | '/courses/$courseCode/section'
    | '/courses/$courseCode/submissions'
    | '/blogs/$courseCode/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/admin'
    | '/app'
    | '/auth'
    | '/courses'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/settings'
    | '/signup'
    | '/teams'
    | '/blogs/new'
    | '/courses/$courseCode'
    | '/doubts/$doubtId'
    | '/profile/$userId'
    | '/teams/$teamId'
    | '/blogs'
    | '/doubts'
    | '/forum'
    | '/profile'
    | '/blogs/$courseCode/$postId'
    | '/courses/$courseCode/section'
    | '/courses/$courseCode/submissions'
    | '/blogs/$courseCode'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/admin'
    | '/app'
    | '/auth'
    | '/courses'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/settings'
    | '/signup'
    | '/teams'
    | '/blogs/new'
    | '/courses_/$courseCode'
    | '/doubts/$doubtId'
    | '/profile/$userId'
    | '/teams_/$teamId'
    | '/blogs/'
    | '/doubts/'
    | '/forum/'
    | '/profile/'
    | '/blogs/$courseCode/$postId'
    | '/courses_/$courseCode_/section'
    | '/courses_/$courseCode_/submissions'
    | '/blogs/$courseCode/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  CoursesRoute: typeof CoursesRoute
  DashboardRoute: typeof DashboardRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TeamsRoute: typeof TeamsRoute
  BlogsNewRoute: typeof BlogsNewRoute
  CoursesCourseCodeRoute: typeof CoursesCourseCodeRoute
  DoubtsDoubtIdRoute: typeof DoubtsDoubtIdRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  DoubtsIndexRoute: typeof DoubtsIndexRoute
  ForumIndexRoute: typeof ForumIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  BlogsCourseCodePostIdRoute: typeof BlogsCourseCodePostIdRoute
  CoursesCourseCodeSectionRoute: typeof CoursesCourseCodeSectionRoute
  CoursesCourseCodeSubmissionsRoute: typeof CoursesCourseCodeSubmissionsRoute
  BlogsCourseCodeIndexRoute: typeof BlogsCourseCodeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/': {
      id: '/forum/'
      path: '/forum'
      fullPath: '/forum/'
      preLoaderRoute: typeof ForumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doubts/': {
      id: '/doubts/'
      path: '/doubts'
      fullPath: '/doubts/'
      preLoaderRoute: typeof DoubtsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams_/$teamId': {
      id: '/teams_/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doubts/$doubtId': {
      id: '/doubts/$doubtId'
      path: '/doubts/$doubtId'
      fullPath: '/doubts/$doubtId'
      preLoaderRoute: typeof DoubtsDoubtIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses_/$courseCode': {
      id: '/courses_/$courseCode'
      path: '/courses/$courseCode'
      fullPath: '/courses/$courseCode'
      preLoaderRoute: typeof CoursesCourseCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/new': {
      id: '/blogs/new'
      path: '/blogs/new'
      fullPath: '/blogs/new'
      preLoaderRoute: typeof BlogsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$courseCode/': {
      id: '/blogs/$courseCode/'
      path: '/blogs/$courseCode'
      fullPath: '/blogs/$courseCode/'
      preLoaderRoute: typeof BlogsCourseCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses_/$courseCode_/submissions': {
      id: '/courses_/$courseCode_/submissions'
      path: '/courses/$courseCode/submissions'
      fullPath: '/courses/$courseCode/submissions'
      preLoaderRoute: typeof CoursesCourseCodeSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses_/$courseCode_/section': {
      id: '/courses_/$courseCode_/section'
      path: '/courses/$courseCode/section'
      fullPath: '/courses/$courseCode/section'
      preLoaderRoute: typeof CoursesCourseCodeSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$courseCode/$postId': {
      id: '/blogs/$courseCode/$postId'
      path: '/blogs/$courseCode/$postId'
      fullPath: '/blogs/$courseCode/$postId'
      preLoaderRoute: typeof BlogsCourseCodePostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  CoursesRoute: CoursesRoute,
  DashboardRoute: DashboardRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TeamsRoute: TeamsRoute,
  BlogsNewRoute: BlogsNewRoute,
  CoursesCourseCodeRoute: CoursesCourseCodeRoute,
  DoubtsDoubtIdRoute: DoubtsDoubtIdRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  DoubtsIndexRoute: DoubtsIndexRoute,
  ForumIndexRoute: ForumIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  BlogsCourseCodePostIdRoute: BlogsCourseCodePostIdRoute,
  CoursesCourseCodeSectionRoute: CoursesCourseCodeSectionRoute,
  CoursesCourseCodeSubmissionsRoute: CoursesCourseCodeSubmissionsRoute,
  BlogsCourseCodeIndexRoute: BlogsCourseCodeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
